/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tcptlibtest_MainActivity */

#ifndef _Included_com_example_tcptlibtest_MainActivity
#define _Included_com_example_tcptlibtest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tcptlibtest_MainActivity
 * Method:    reg
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_tcptlibtest_MainActivity_reg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_tcptlibtest_MainActivity
 * Method:    auth
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_tcptlibtest_MainActivity_auth
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
